# Generated by Django 6.0.1 on 2026-01-13 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='job_id',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
    ]
